// Custom Worker entry that wraps the OpenNext-generated worker to add a
// `scheduled` handler. The generated `.open-next/worker.js` only exports
// `fetch` (+ Durable Object classes), so a Cloudflare Cron Trigger would fire
// into a void without this. We re-export the DO classes unchanged so their
// bindings keep resolving, delegate `fetch` to OpenNext, and add `scheduled`
// which pings our own cron route to void lapsed PromptPay QR codes.
//
// Rebuilt each deploy: `.open-next/worker.js` is regenerated by
// `opennextjs-cloudflare build`, but this wrapper only imports from it — safe.
import openNextWorker from './.open-next/worker.js';

export { DOQueueHandler } from './.open-next/worker.js';
export { DOShardedTagCache } from './.open-next/worker.js';
export { BucketCachePurge } from './.open-next/worker.js';

interface CronEnv {
  SITE_URL?: string;
  CRON_SECRET?: string;
}

export default {
  fetch: openNextWorker.fetch,

  // Cron Trigger (see wrangler.toml [triggers]). Runs every minute: hit the
  // internal sweep that releases the seat of any hold past its 10-min window
  // and retries the refund of money that arrived after it. The QR itself cannot
  // be cancelled — Beam offers no endpoint for it — so a late scan is money to
  // give back rather than something to block.
  async scheduled(_event: unknown, env: CronEnv, ctx: { waitUntil(p: Promise<unknown>): void }) {
    const base = env.SITE_URL || 'https://allsoullearn.com';
    ctx.waitUntil(
      fetch(`${base}/api/cron/expire-holds`, {
        headers: { 'x-cron-secret': env.CRON_SECRET || '' },
      }).catch((e) => console.error('scheduled expire-holds failed', e)),
    );
  },
};
